name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool pkg-config

      - name: Configure
        run: ./configure

      - name: Make
        run: make

      - name: Make Check
        run: make check

      - name: Clean before Distcheck
        run: git clean -fdx

      - name: Make Distcheck
        run: make distcheck
